#!/usr/bin/env python3
"""Inline the web fonts so a page renders identically with no network at all.

The tracker and the exported brief both link Google Fonts. Online that is fine.
Offline — a laptop in a deposition, a PDF printed from a machine behind a
firewall, an email attachment opened on a plane — the link silently fails and
the page falls back to system faces. Nothing breaks, but the document is not
the document that was reviewed.

This fetches the exact faces the pages use, embeds them as base64 ``@font-face``
rules, and swaps out the ``<link>`` tags:

    python3 scripts/embed_fonts.py laws.html
    python3 scripts/embed_fonts.py out/laws-brief.html --out out/brief-offline.html

Fonts are cached under ``data/fonts/`` on first run, so later builds need no
network and produce byte-identical output.

Licensing: Archivo, Newsreader, IBM Plex Sans and IBM Plex Mono are all under
the SIL Open Font License 1.1, which permits embedding in a document. The
generated CSS carries the attribution.
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import re
import sys
import urllib.request
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CACHE = ROOT / "data" / "fonts"

# Google serves woff2 only to a browser-ish UA; with the default urllib string
# it hands back woff, which is roughly 30% larger for no benefit.
UA = ("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) "
      "Chrome/120.0.0.0 Safari/537.36")

# Only the faces the pages actually set. The stylesheets asked for seventeen;
# the CSS uses nine. Each unused weight is a wasted 15-25 KB once embedded.
#
# These go through the v1 CSS API rather than css2 on purpose. css2 serves the
# variable font whatever weight you pin, and Newsreader's optical-size axis
# makes that 90 KB for a face used on six headlines; the v1 endpoint hands back
# a static instance at 22 KB for the identical rendering at one weight.
FACES = [
    ("Archivo", "700", None),
    ("Archivo", "800", None),
    ("Newsreader", "400", None),
    ("Newsreader", "400italic", "italic"),
    ("IBM+Plex+Sans", "400", None),
    ("IBM+Plex+Sans", "500", None),
    ("IBM+Plex+Sans", "600", None),
    ("IBM+Plex+Mono", "400", None),
    ("IBM+Plex+Mono", "500", None),
]

# `latin` carries the marks legal writing actually depends on — § — – ' × ½ —
# and today's corpus needs nothing beyond it. `latin-ext` costs about as much
# again per face and buys only accented characters, so it is opt-in. The
# coverage check below fails loudly if a drop ever starts needing it.
DEFAULT_SUBSETS = ("latin",)

LICENSE_NOTE = """/* Embedded web fonts — no network required.
   Archivo (Omnibus-Type), Newsreader (Production Type), IBM Plex Sans and
   IBM Plex Mono (IBM) are licensed under the SIL Open Font License 1.1,
   which permits embedding. https://scripts.sil.org/OFL
   Generated by scripts/embed_fonts.py — do not hand-edit. */"""

BLOCK_RE = re.compile(
    r"/\*\s*(?P<subset>[\w-]+)\s*\*/\s*@font-face\s*\{(?P<body>[^}]*)\}", re.S)
SRC_RE = re.compile(r"url\((?P<url>https://fonts\.gstatic\.com/[^)]+)\)")
PROP_RE = lambda name: re.compile(rf"{name}\s*:\s*([^;]+);")


def fetch(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=45) as r:
        return r.read()


def cached(url: str) -> bytes:
    """Fetch once, keep forever. gstatic URLs are content-addressed already."""
    CACHE.mkdir(parents=True, exist_ok=True)
    key = CACHE / (hashlib.sha256(url.encode()).hexdigest()[:20] + ".woff2")
    if key.exists():
        return key.read_bytes()
    blob = fetch(url)
    key.write_bytes(blob)
    return blob


def face_css(family: str, weight: str, style: str | None,
             subsets: tuple[str, ...]) -> tuple[str, int, list[str]]:
    """Return the @font-face rules for one face, its byte cost, and its ranges."""
    css = fetch(f"https://fonts.googleapis.com/css?family={family}:{weight}"
                f"&display=swap").decode("utf-8")
    out, raw, ranges = [], 0, []
    for m in BLOCK_RE.finditer(css):
        if m.group("subset") not in subsets:
            continue
        body = m.group("body")
        url_m = SRC_RE.search(body)
        if not url_m:
            continue
        blob = cached(url_m.group("url"))
        raw += len(blob)
        b64 = base64.b64encode(blob).decode("ascii")

        def prop(name, default=""):
            p = PROP_RE(name).search(body)
            return p.group(1).strip() if p else default

        rng = prop("unicode-range")
        if rng:
            ranges.append(rng)
        out.append(
            f"@font-face{{font-family:'{prop('font-family').strip(chr(39))}';"
            f"font-style:{style or prop('font-style', 'normal')};"
            f"font-weight:{prop('font-weight', '400')};font-display:swap;"
            f"src:url(data:font/woff2;base64,{b64}) format('woff2');"
            + (f"unicode-range:{rng};" if rng else "") + "}")
    if not out:
        raise RuntimeError(f"no {'/'.join(subsets)} face returned for "
                           f"{family}:{weight} — check the weight spelling")
    return "".join(out), raw, ranges


RANGE_RE = re.compile(r"U\+([0-9A-Fa-f]+)(?:-([0-9A-Fa-f]+))?")


def uncovered(text: str, ranges: list[str]) -> Counter:
    """Characters in the document that no embedded face can draw.

    Embedding is for fidelity, so a character that silently falls back defeats
    the point. Better to name it now than to find it in a printed brief.
    """
    spans = []
    for r in ranges:
        for lo, hi in RANGE_RE.findall(r):
            spans.append((int(lo, 16), int(hi or lo, 16)))
    missing = Counter()
    for ch in text:
        cp = ord(ch)
        if cp < 0x20 or any(lo <= cp <= hi for lo, hi in spans):
            continue
        missing[ch] += 1
    return missing


LINK_RE = re.compile(
    r"[ \t]*<link[^>]*(?:fonts\.googleapis\.com|fonts\.gstatic\.com)[^>]*>\n?", re.I)


def embed(html: str, subsets: tuple[str, ...]) -> tuple[str, int, int, list[str]]:
    blocks, raw_total, ranges = [], 0, []
    for family, weight, style in FACES:
        css, raw, rngs = face_css(family, weight, style, subsets)
        blocks.append(css)
        raw_total += raw
        ranges.extend(rngs)
        print(f"  {family.replace('+', ' '):16} {weight:12} {raw / 1024:6.1f} KB",
              file=sys.stderr)
    style_tag = f"<style>\n{LICENSE_NOTE}\n" + "\n".join(blocks) + "\n</style>\n"

    if not LINK_RE.search(html):
        raise RuntimeError("no Google Fonts <link> found — already embedded?")
    # Replace the first link, drop the rest (preconnects included: nothing to
    # connect to once the bytes are in the file).
    html, n = LINK_RE.subn(lambda m: "", html)
    head_anchor = html.index("<style>")
    html = html[:head_anchor] + style_tag + html[head_anchor:]
    return html, raw_total, n, ranges


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("target", type=Path, help="HTML file to rewrite")
    ap.add_argument("--out", type=Path, default=None,
                    help="write here instead of in place")
    ap.add_argument("--subsets", default=",".join(DEFAULT_SUBSETS),
                    help="comma-separated Google subsets to embed "
                         f"(default {','.join(DEFAULT_SUBSETS)}; add latin-ext "
                         "for accented characters, at roughly double the size)")
    args = ap.parse_args()
    subsets = tuple(s.strip() for s in args.subsets.split(",") if s.strip())

    if not args.target.exists():
        print(f"no file at {args.target}", file=sys.stderr)
        return 1
    html = args.target.read_text(encoding="utf-8")
    before = len(html.encode())

    print(f"Fetching faces ({', '.join(subsets)}):", file=sys.stderr)
    try:
        out_html, raw, links, ranges = embed(html, subsets)
    except (RuntimeError, OSError) as exc:
        print(f"failed: {exc}", file=sys.stderr)
        return 1

    dest = args.out or args.target
    dest.write_text(out_html, encoding="utf-8")
    after = len(out_html.encode())
    print(f"\n{len(FACES)} faces, {raw / 1024:.0f} KB of woff2 "
          f"-> {(after - before) / 1024:+.0f} KB on the page "
          f"({before / 1024:.0f} -> {after / 1024:.0f} KB)", file=sys.stderr)
    print(f"removed {links} font <link> tag(s); wrote {dest}", file=sys.stderr)

    # Visible text only — base64 payloads and CSS would swamp the signal.
    visible = re.sub(r"<(script|style)\b.*?</\1>", " ", out_html, flags=re.S | re.I)
    visible = re.sub(r"<[^>]+>", " ", visible)
    missing = uncovered(visible, ranges)
    if missing:
        print("\nCharacters no embedded face covers — these fall back to a "
              "system font:", file=sys.stderr)
        for ch, n in missing.most_common(12):
            print(f"  {ch!r:8} U+{ord(ch):04X} x{n}", file=sys.stderr)
        print("  Add --subsets latin,latin-ext if these are letters rather than "
              "symbols.", file=sys.stderr)
    else:
        print("Coverage: every character in the document is drawn by an "
              "embedded face.", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
